### ISSUE TITLE
VoiceOver registering the University logo as an "unlabeled image"

### ISSUE THREAD

**Issue by brionwolf** [UMD-Digital/elements-footer-small#4]
Came up when I was testing [homecoming](https://github.com/UMD-Digital/homecoming/tree/dev).  
For now, VoiceOver does read out the url, can't speak for other screen readers.

<img width="750" alt="screenshot of footer element with voiceOver dialogue stating the image is unlabeled" src="https://user-images.githubusercontent.com/5532234/134203303-045e3196-0157-4a2c-99ea-38b7ea820c4f.png">

**Comment by magnessjo** [comment]
@brionwolf fixed with https://github.com/UMD-Digital/elements-footer-small/commit/d2c7ba922bb1f23357374c617ce757f5d707984f.
